#!/usr/bin/env bash

read -p 'Please enter your organization name: ' ORG_NAME
read -p 'Please enter your workspace name: ' WSPACE_NAME
read -p 'Please enter your API user token: ' TOKEN

# The following lines should are left for development purposes
#ORG_NAME=HiveCorpp
#WSPACE_NAME=ExtIP
#TOKEN=

export ORG_NAME=${ORG_NAME}
export WSPACE_NAME=${WSPACE_NAME}
export TOKEN=${TOKEN}

# Variable to shorten URLs
export TFE=https://app.terraform.io/api/v2

# The following block of code will etch your workspace ID from TFE

export WSPACE_ID="$(curl \
  --header "Authorization: Bearer ${TOKEN}" \
  --header "Content-Type: application/vnd.api+json" \
  ${TFE}/organizations/${ORG_NAME}/workspaces/${WSPACE_NAME} 2>/dev/null | jq '.data | .id' | tr -d \")"

# The following block of code is going to retrieve the current run ID of your TFE Workspace
export CURRENT_RUN="$(curl \
  --header "Authorization: Bearer ${TOKEN}" \
  --header "Content-Type: application/vnd.api+json" \
  ${TFE}/workspaces/${WSPACE_ID}/runs 2>/dev/null | jq '.data | .[0] | .id' | tr -d \")"


# The following is added for debugging purposes. Will be removed in the final version

echo -e "Your Current Run ID is: \n ${CURRENT_RUN} \n"

# The following block of code is going to retrieve the configuration ID of the current run on your TFE Workspace

export CONF="$(curl \
  --header "Authorization: Bearer ${TOKEN}" \
  --header "Content-Type: application/vnd.api+json" \
  ${TFE}/runs/${CURRENT_RUN}/configuration-version 2>/dev/null | jq '.data | .id' | tr -d \")"

# The following block of code will create an operations options menu

echo -e "\nPlease choose an operation from the list below: \n \
    1) Run and apply operation \n \
    2) Get variable info \n \
    3) Retrieve outputs generated by your last TFE run\n \
    4) Run a destroy operation\n \
    5) Exit \n
\n \
    Please enter a number in the range 1-4 that corresponds to your choice or enter 5 to exit \n \
   "
# The following block of code reads user input and runs an operation according to the selected option

while read -p 'Please choose option 1-4, or 5 to exit: ' CHOICE; do
    if [ ${CHOICE} == 1 ]; then
         echo -e "\nYou chose a run and apply operation \n"
         bash /vagrant/scripts/run_plan_apply.sh
         break
    elif [ ${CHOICE} == 2 ]; then
         echo -e "\nYou chose 'Get variable info' option \n"
         bash /vagrant/scripts/tfe_var_manage.sh
         break
    elif [ ${CHOICE} == 3 ]; then
         echo -e "\nYou chose to retrieve the outputs from your latest run\n"
         bash /vagrant/scripts/retrieve_output.sh
         break
    elif [ ${CHOICE} == 4 ]; then
         echo -e "\nYou chose to run a destroy operation\n"
         bash /vagrant/scripts/run_destroy.sh
         break
    elif [ ${CHOICE} == 5 ]; then
         echo -e "\nGoodbye! Please have a nice day.\n"
         break
    else
         echo -e "\n INVALID INPUT\n"
         continue
    fi
done
